# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Farmlytics
                                 A QGIS plugin
 Farmlytics is a QGIS plugin designed to enhance agricultural analysis through intuitive visualization and comparison of farm-level NDVI data. Select farms, view their NDVI trends across growing cycles, and explore key phenological markers like SOS, EOS, and peak NDVI. Interact with feature tables and plots to make informed decisions—all within the QGIS environment.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-23
        copyright            : (C) 2025 by Mahathi S
        email                : mahathisarp@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Farmlytics class from file Farmlytics.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Farmlytics import Farmlytics
    return Farmlytics(iface)
